# Generated by Django 5.1.1 on 2024-10-01 04:58

import cats.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название породы"),
                ),
            ],
            options={
                "verbose_name": "Порода",
                "verbose_name_plural": "Породы",
            },
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя котика")),
                ("color", models.CharField(max_length=150, verbose_name="Цвет котика")),
                (
                    "birth_date",
                    models.DateField(
                        validators=[cats.validators.validate_birth_date],
                        verbose_name="Дата рождения котика",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание котика")),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cats",
                        to="cats.breed",
                        verbose_name="Порода котика",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хозяин котика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Котик",
                "verbose_name_plural": "Котики",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "owner"), name="unique_name_owner"
                    )
                ],
            },
        ),
    ]
